# Generated by Django 3.2.8 on 2022-01-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Quotet Iteam',
            },
        ),
    ]
